version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=newsfeed
      - DB_USERNAME=daemon
      - DB_PASSWORD=7359e8xqyQtpyF9s
  database:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: newsfeed
      MYSQL_USER: daemon
      MYSQL_PASSWORD: 7359e8xqyQtpyF9s
    ports:
      - "3306:3306"
